# Generated by Django 2.1.2 on 2018-11-07 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceAccounts',
            fields=[
                ('Id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('Number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('Id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('Code', models.IntegerField(unique=True)),
                ('Description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('Id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('Id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=200)),
                ('date_since', models.DateField()),
                ('date_to', models.DateField()),
                ('BanksName', models.CharField(max_length=100)),
                ('CurrencyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExcelManager.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('Id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('BalanceOfInputAssets', models.FloatField()),
                ('BalanceOfOutputAssets', models.FloatField()),
                ('BalanceOfInputLiabilities', models.FloatField()),
                ('BalanceOfOutputLiabilities', models.FloatField()),
                ('CashFlowDebit', models.FloatField()),
                ('CashFlowCredit', models.FloatField()),
                ('BalanceAccountsId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExcelManager.BalanceAccounts')),
                ('FileId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExcelManager.Files')),
            ],
        ),
        migrations.AddField(
            model_name='balanceaccounts',
            name='ClassId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExcelManager.Classes'),
        ),
    ]
